[theme]
primaryColor = "#4CAF50"  # Verde principal
backgroundColor = "#ffffff"  # Branco como cor de fundo principal
secondaryBackgroundColor = "#f0f0f5"  # Cor de fundo secundária
textColor = "#31333F"  # Cor do texto
font = "sans serif"  # Fonte principal
